### ISSUE TITLE
Feature proposal: Select ALSA PCM output device using environment variables.

### ISSUE THREAD

**Issue by defcronyke** [mozilla/cubeb#635]
I propose that we should be able to select the desired ALSA PCM output device, rather than the current limitation of only outputting to the system's default ALSA device, and I have added a way to do it by setting any one of the following environment variables, for example:
```shell
ALSA_PCM_DEVICE="jackvol"
ALSA_PCM_CARD="jackvol"
ALSA_CARD="jackvol"
```

The way I implemented it, the first of whichever of the env vars that's set, in the order listed above, will be used by cubeb_alsa for PCM output, and the value will be assumed to be an ALSA "plug:" type device, except in the case where the value is the string "default", in which case no assumption will be made about the type of ALSA device and it will just do the ALSA open routine using the string "default". If none of the env vars are set, it will also just use the string "default".

You can also change the type of ALSA device by setting the following environment variable, for example:
```shell
ALSA_PCM_TYPE="plughw:" ALSA_CARD="CARD=MK2,DEV=0"
```

I implemented this with the intention of fixing some bug I thought I had found in Firefox which turned out to be my own .asoundrc configuration mistake, but since I think this feature could be quite useful anyway, I decided to propose it as a feature proposal instead of a bugfix. It could be especially useful to any Linux Firefox users who don't use PulseAudio, or who use the alsa-jack sink feature like I do.

I'll submit a PR for it now, and then I look forward to any feedback. I hope you'll consider it, because I would love to have this feature.

**Comment by kinetiknz** [comment]
Thanks for looking into this and suggesting a fix with a nice patch.  I understand the potential need to pass a specific device string to ALSA other than the hardcoded "default", although I wonder if passing a string through the cubeb API from (for example) Firefox prefs instead of using environment variables would be a better approach.  I'm not completely opposed to using environment variables, so we can discuss this further.

It looks like these ALSA_* environment variables are already used inside ALSA - looking at the standard configs shipped with alsa-lib, many of them already reference these environment variables.  If sticking with environment variables, do we need to use a prefixed name (e.g. CUBEB_ALSA_CARD) to avoid unexpected interactions with the existing uses of these variables inside ALSA?

**Comment by defcronyke** [comment]
> ... I wonder if passing a string through the cubeb API from (for example) Firefox prefs instead of using environment variables would be a better approach. ...

That sounds like a good idea actually. It's probably a cleaner way than having cubeb reacting to the environment, although it would be a more invasive change to the code, which is why I did it with the env instead initially. I would be willing to make the changes to do it that way instead if you think it's a good idea to be updating the cubeb API and also the Firefox config system to support this. Maybe some setting similar to `media.cubeb.backend.alsa.output = "plug:jackvol"` for example?

> It looks like these ALSA_* environment variables are already used inside ALSA - looking at the standard configs shipped with alsa-lib, many of them already reference these environment variables. If sticking with environment variables, do we need to use a prefixed name (e.g. CUBEB_ALSA_CARD) to avoid unexpected interactions with the existing uses of these variables inside ALSA?

If we do the above instead of env vars, then we don't need to decide this, but it's a good point that these particular vars may cause some problems. Their behaviour is supposed to cause ALSA "default" and some other device aliases to change actually, but then those changes are overridden by anything existing in .asoundrc, so because I had my own customized .asoundrc, I probably wasn't noticing any change caused when setting these env vars, it definitely might cause weird problems to use the same ones.

I'd rather not use env vars actually if you'll be okay with some changes to the cubeb API and if Firefox people will allow another config setting for it.

Let me know what you think, and if you think it'd be considered, I could go ahead and work on it in the next day or so.

**Comment by kinetiknz** [comment]
The cubeb changes needed for this are already present: cubeb_devid is treated as an ALSA device string [here](https://github.com/mozilla/cubeb/blob/master/src/cubeb_alsa.c#L965) and passed to [`snd_pcm_open`](https://github.com/mozilla/cubeb/blob/master/src/cubeb_alsa.c#L1021).

On the Gecko side, it's a matter of adding a new `#ifdef MOZ_ALSA` pref `media.cubeb.backend.alsa.output` that is passed as a `cubeb_devid` [here](https://searchfox.org/mozilla-central/source/dom/media/GraphDriver.cpp#680) and [here](https://searchfox.org/mozilla-central/source/dom/media/AudioStream.cpp#328).  The existing test-only `media.cubeb.output_device` used by GraphDriver is similar, but uses device enumeration to map the pref string to a `cubeb_devid`.  Since the ALSA backend lacks a complete `cubeb_enumerate_devices` implementation (it just returns a "default" input and output device), the simplest approach would be to treat the  `media.cubeb.backend.alsa.output` pref string as a valid `cubeb_devid` and pass it through directly.

**Comment by defcronyke** [comment]
> The cubeb changes needed for this are already present: cubeb_devid is treated as an ALSA device string [here](https://github.com/mozilla/cubeb/blob/master/src/cubeb_alsa.c#L965) and passed to [`snd_pcm_open`](https://github.com/mozilla/cubeb/blob/master/src/cubeb_alsa.c#L1021).

Okay perfect, thanks for finding it.

> On the Gecko side, it's a matter of adding a new `#ifdef MOZ_ALSA` pref `media.cubeb.backend.alsa.output` that is passed as a `cubeb_devid` [here](https://searchfox.org/mozilla-central/source/dom/media/GraphDriver.cpp#680) and [here](https://searchfox.org/mozilla-central/source/dom/media/AudioStream.cpp#328). The existing test-only `media.cubeb.output_device` used by GraphDriver is similar, but uses device enumeration to map the pref string to a `cubeb_devid`. Since the ALSA backend lacks a complete `cubeb_enumerate_devices` implementation (it just returns a "default" input and output device), the simplest approach would be to treat the `media.cubeb.backend.alsa.output` pref string as a valid `cubeb_devid` and pass it through directly.

This seems like a good way to proceed, I'm trying it now and I'll let you know once it's working. Where should I raise this issue for proposing the changes to libpref and the dom/media stuff?

**Comment by padenot** [comment]
> This seems like a good way to proceed, I'm trying it now and I'll let you know once it's working. Where should I raise this issue for proposing the changes to libpref and the dom/media stuff?

https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Audio%2FVideo%3A%20cubeb is an URL with the correct component for cubeb-related stuff in Firefox, you can log in with your github account.

**Comment by kinetiknz** [comment]
Closing this since there are no changes needed on the cubeb side.
